# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    paths: papers.csv

name: render_papers

jobs:
  render-rmarkdown:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-renv@v2
      
      - name: Install rmarkdown
        run: Rscript -e 'install.packages(c("rmarkdown","DT"))'
      - name: Render new html
        run: Rscript -e 'rmarkdown::render("index.Rmd")'
      - name: Commit results
        run: |
          git commit -a -m 'Re-build index.html' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
