# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
    paths:
      - index.Rmd

name: Render index

jobs:
  render:
    name: Render index
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Install rmarkdown
        run: Rscript -e 'install.packages("rmarkdown")'
      - name: Render README
        run: Rscript -e 'rmarkdown::render("index.Rmd")'
      - name: Commit results
        run: |
          git commit index.html -m 'Re-build index.Rmd' || echo "No changes to commit"
          git push origin || echo "No changes to commit"


