on:
  push:
    paths:
      - papers.csv
      - journal_list.csv

name: Render my document

jobs:
  render:
    name: Render my document
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - uses: r-lib/actions/setup-tinytex@v1
      - name: Install rmarkdown
        run: Rscript -e 'install.packages(c("rmarkdown","DT"))'
      - name: Render my document to all types
        run: Rscript -e 'rmarkdown::render("index.Rmd", output_format = "html_document")'
      - name: Commit results
        run: |
          git add index.html
          git commit -m 'Re-build my-document' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
